title: "Status Monitor"

server:
  port: 3001
  host: "0.0.0.0"
  checkInterval: 1 # minutes

database:
  path: "./status.db"
  cleanupDays: 90

notification:
  appriseApiServer: "https://apprise.example.com/notify"
  recipientUrl: "tgram://bottoken/ChatID"
  timeZone: "Asia/Shanghai"
  gracePeriod: 5 # minutes
  skipNotificationIds: []

monitors:
  - id: "example-site"
    name: "Example Website"
    method: "GET"
    target: "https://example.com"
    tooltip: "Example website health check"
    statusPageLink: "https://example.com"
    hideLatencyChart: false
    expectedCodes: [200]
    timeout: 10000

  - id: "example-api"
    name: "Example API"
    method: "GET"
    target: "https://api.example.com/health"
    tooltip: "Example API health check"
    expectedCodes: [200]
    timeout: 5000
    headers:
      User-Agent: "StatusMonitor/1.0"
      Authorization: "Bearer your-token-here"

  - id: "example-tcp"
    name: "Example SSH"
    method: "TCP_PING"
    target: "example.com:22"
    tooltip: "SSH connectivity check"
    timeout: 5000